// Curated, realistic Los Angeles rental listings. Real neighborhoods, real
// streets, and rents calibrated to the 2024–2025 LA market. This is demo data,
// not live inventory — use the RentCast sync (src/lib/rentcast.ts) for live
// listings.

export interface SeedListing {
  title: string;
  address: string;
  city: string;
  state: string;
  neighborhood: string;
  rent: number;
  bedrooms: number;
  bathrooms: number;
  sqft: number;
  amenities: string;
  petFriendly: boolean;
  furnished: boolean;
  description: string;
  commuteNotes: string;
  latitude: number;
  longitude: number;
}

export const LA_LISTINGS: SeedListing[] = [
  // Downtown LA
  { title: "Loft-style 1BR in the Historic Core", address: "650 S Spring St", city: "Los Angeles", state: "CA", neighborhood: "Downtown LA", rent: 2450, bedrooms: 1, bathrooms: 1, sqft: 820, amenities: "Rooftop pool, Gym, In-unit laundry, Concierge", petFriendly: true, furnished: false, description: "Open-plan loft with 12-ft ceilings and original brick in a restored 1920s bank building. Walk to the Broadway theaters, Grand Central Market, and the Metro.", commuteNotes: "2 blocks to Pershing Square Metro (B/D lines); 20 min to Union Station.", latitude: 34.0466, longitude: -118.2517 },
  { title: "Modern studio on Grand Ave", address: "1100 S Grand Ave", city: "Los Angeles", state: "CA", neighborhood: "South Park, DTLA", rent: 1950, bedrooms: 0, bathrooms: 1, sqft: 540, amenities: "Gym, Pool, Rooftop deck, Parking", petFriendly: false, furnished: false, description: "Efficient studio in a glass high-rise steps from Crypto.com Arena and L.A. Live. Floor-to-ceiling windows with city views.", commuteNotes: "Walk to Pico Metro station; quick 110 freeway access.", latitude: 34.0395, longitude: -118.2645 },
  { title: "Sunny 2BR near the Arts District", address: "923 E 3rd St", city: "Los Angeles", state: "CA", neighborhood: "Arts District, DTLA", rent: 3650, bedrooms: 2, bathrooms: 2, sqft: 1180, amenities: "In-unit laundry, Stainless appliances, Balcony, EV charging", petFriendly: true, furnished: false, description: "Industrial-chic 2BR among the galleries, breweries, and cafes of the Arts District. Polished concrete floors and a private balcony.", commuteNotes: "10 min drive to Union Station; bikeable to Little Tokyo.", latitude: 34.0443, longitude: -118.2335 },

  // Koreatown
  { title: "Spacious 1BR on Wilshire", address: "3700 Wilshire Blvd", city: "Los Angeles", state: "CA", neighborhood: "Koreatown", rent: 2100, bedrooms: 1, bathrooms: 1, sqft: 760, amenities: "Pool, Gym, Doorman, Parking", petFriendly: true, furnished: false, description: "Bright corner unit in a mid-century tower surrounded by K-Town's 24-hour restaurants, cafes, and spas. Hardwood floors throughout.", commuteNotes: "Wilshire/Western Metro (D line) 3 blocks away; 15 min to DTLA.", latitude: 34.0617, longitude: -118.3009 },
  { title: "Renovated studio near Vermont", address: "2920 W 8th St", city: "Los Angeles", state: "CA", neighborhood: "Koreatown", rent: 1650, bedrooms: 0, bathrooms: 1, sqft: 480, amenities: "Central AC, On-site laundry, Controlled access", petFriendly: false, furnished: false, description: "Freshly updated studio with quartz counters and new flooring. Unbeatable access to Wiltern shows and late-night eats.", commuteNotes: "Walk to Wilshire/Vermont Metro; easy 101 access.", latitude: 34.0573, longitude: -118.2942 },
  { title: "2BR with city views in K-Town", address: "680 S Normandie Ave", city: "Los Angeles", state: "CA", neighborhood: "Koreatown", rent: 2850, bedrooms: 2, bathrooms: 2, sqft: 1050, amenities: "Rooftop lounge, Gym, In-unit laundry, Parking", petFriendly: true, furnished: false, description: "Top-floor 2BR in a newer building with a rooftop lounge overlooking the Hollywood sign. Open kitchen with island seating.", commuteNotes: "5 min to Metro D line; central to the whole city.", latitude: 34.0606, longitude: -118.2997 },

  // Silver Lake
  { title: "Hillside 1BR off Sunset", address: "2715 Sunset Blvd", city: "Los Angeles", state: "CA", neighborhood: "Silver Lake", rent: 2550, bedrooms: 1, bathrooms: 1, sqft: 720, amenities: "Hardwood floors, Dishwasher, Shared patio, Pet area", petFriendly: true, furnished: false, description: "Charming Spanish-style unit walkable to the Silver Lake reservoir, Intelligentsia, and Sunset Junction boutiques.", commuteNotes: "15 min to DTLA; multiple bus lines on Sunset.", latitude: 34.0762, longitude: -118.2603 },
  { title: "Designer 2BR near the Reservoir", address: "1840 Silver Lake Blvd", city: "Los Angeles", state: "CA", neighborhood: "Silver Lake", rent: 3900, bedrooms: 2, bathrooms: 2, sqft: 1240, amenities: "In-unit laundry, Private yard, Smart home, EV charging", petFriendly: true, furnished: false, description: "Architectural 2BR with walls of glass opening to a private yard. Steps from the Silver Lake Meadow and weekend farmers market.", commuteNotes: "Bike path around the reservoir; 20 min to DTLA.", latitude: 34.0871, longitude: -118.2701 },

  // Echo Park
  { title: "Cozy studio by Echo Park Lake", address: "1430 Echo Park Ave", city: "Los Angeles", state: "CA", neighborhood: "Echo Park", rent: 1750, bedrooms: 0, bathrooms: 1, sqft: 500, amenities: "Hardwood floors, On-site laundry, Garden", petFriendly: true, furnished: false, description: "Bungalow-court studio a block from the lotus blooms of Echo Park Lake. Quiet, leafy street with a shared garden.", commuteNotes: "Walk to Sunset Blvd buses; 12 min to DTLA.", latitude: 34.0782, longitude: -118.2606 },
  { title: "Bright 1BR near the Junction", address: "1525 Echo Park Ave", city: "Los Angeles", state: "CA", neighborhood: "Echo Park", rent: 2300, bedrooms: 1, bathrooms: 1, sqft: 690, amenities: "Dishwasher, In-unit laundry, Balcony, Parking", petFriendly: true, furnished: false, description: "Updated 1BR with treetop views and a private balcony. Around the corner from indie coffee shops and Dodger Stadium.", commuteNotes: "10 min to DTLA; close to the 101 and 110.", latitude: 34.0814, longitude: -118.2607 },

  // Hollywood
  { title: "High-rise 1BR on Vine", address: "1601 Vine St", city: "Los Angeles", state: "CA", neighborhood: "Hollywood", rent: 2750, bedrooms: 1, bathrooms: 1, sqft: 780, amenities: "Pool, Gym, Rooftop deck, Concierge, Parking", petFriendly: true, furnished: false, description: "Resort-style living at Hollywood & Vine with a heated pool and skyline views. Walk to the Pantages and the Metro.", commuteNotes: "Hollywood/Vine Metro (B line) at your door; 18 min to DTLA.", latitude: 34.1016, longitude: -118.3267 },
  { title: "Studio steps from the Walk of Fame", address: "6677 Franklin Ave", city: "Los Angeles", state: "CA", neighborhood: "Hollywood", rent: 1850, bedrooms: 0, bathrooms: 1, sqft: 520, amenities: "Pool, On-site laundry, Controlled access", petFriendly: false, furnished: true, description: "Furnished studio in a classic courtyard building below the Hollywood Hills. Move-in ready with a turnkey furniture package.", commuteNotes: "Buses on Franklin and Hollywood; 5 min to the 101.", latitude: 34.1048, longitude: -118.3324 },
  { title: "3BR townhome near Runyon", address: "2120 N Cahuenga Blvd", city: "Los Angeles", state: "CA", neighborhood: "Hollywood Hills", rent: 5200, bedrooms: 3, bathrooms: 2.5, sqft: 1850, amenities: "Two-car garage, In-unit laundry, Private roof deck, Fireplace", petFriendly: true, furnished: false, description: "Three-story townhome at the base of Runyon Canyon with a private roof deck and canyon views. Perfect for roommates.", commuteNotes: "5 min to Hollywood Blvd; quick canyon access to the Valley.", latitude: 34.1124, longitude: -118.3387 },

  // West Hollywood
  { title: "Chic 1BR on Santa Monica Blvd", address: "8530 Santa Monica Blvd", city: "West Hollywood", state: "CA", neighborhood: "West Hollywood", rent: 2950, bedrooms: 1, bathrooms: 1, sqft: 800, amenities: "Pool, Gym, Rooftop lounge, EV charging, Concierge", petFriendly: true, furnished: false, description: "Sleek 1BR in the heart of WeHo's nightlife and design district. Floor-to-ceiling windows and a chef's kitchen.", commuteNotes: "Walkable to Sunset Strip; 15 min to Beverly Hills.", latitude: 34.0837, longitude: -118.3792 },
  { title: "2BR near the Design District", address: "650 N San Vicente Blvd", city: "West Hollywood", state: "CA", neighborhood: "West Hollywood", rent: 4400, bedrooms: 2, bathrooms: 2, sqft: 1300, amenities: "Valet parking, Pool, Gym, In-unit laundry, Concierge", petFriendly: true, furnished: false, description: "Luxury 2BR steps from the Pacific Design Center and Cedars-Sinai. Spa-like baths and a wraparound terrace.", commuteNotes: "Central to Beverly Hills and Hollywood; ample bus service.", latitude: 34.0830, longitude: -118.3853 },

  // Santa Monica
  { title: "Ocean-adjacent 1BR off Montana", address: "1010 Montana Ave", city: "Santa Monica", state: "CA", neighborhood: "Santa Monica", rent: 3400, bedrooms: 1, bathrooms: 1, sqft: 760, amenities: "In-unit laundry, Hardwood floors, Parking, Bike storage", petFriendly: true, furnished: false, description: "Bright 1BR on coveted Montana Ave, a short stroll to the beach, boutiques, and the Sunday farmers market.", commuteNotes: "10 min walk to the beach; near Big Blue Bus lines.", latitude: 34.0277, longitude: -118.4978 },
  { title: "Studio near Third Street Promenade", address: "1437 6th St", city: "Santa Monica", state: "CA", neighborhood: "Santa Monica", rent: 2300, bedrooms: 0, bathrooms: 1, sqft: 540, amenities: "Pool, On-site laundry, Controlled access, Parking", petFriendly: false, furnished: false, description: "Updated studio two blocks from the Promenade and the pier. Walk to everything; leave the car at home.", commuteNotes: "Expo Line terminus 8 min away; direct train to DTLA.", latitude: 34.0182, longitude: -118.4938 },
  { title: "Beachside 2BR on Ocean Ave", address: "120 Ocean Ave", city: "Santa Monica", state: "CA", neighborhood: "Santa Monica", rent: 5400, bedrooms: 2, bathrooms: 2, sqft: 1400, amenities: "Ocean views, Pool, Gym, Concierge, Valet", petFriendly: true, furnished: false, description: "Front-row 2BR with whitewater ocean views and sunsets every night. Steps from the Palisades and the pier.", commuteNotes: "Expo Line nearby; walk or bike the beach path for miles.", latitude: 34.0119, longitude: -118.4974 },

  // Venice
  { title: "Creative 1BR near Abbot Kinney", address: "1245 Abbot Kinney Blvd", city: "Los Angeles", state: "CA", neighborhood: "Venice", rent: 3100, bedrooms: 1, bathrooms: 1, sqft: 740, amenities: "In-unit laundry, Private patio, Skylights, Bike storage", petFriendly: true, furnished: false, description: "Light-filled 1BR with skylights on the 'coolest block in America.' Surrounded by boutiques, coffee, and the canals.", commuteNotes: "Bike to the beach in 6 min; walk to Rose Ave cafes.", latitude: 33.9905, longitude: -118.4673 },
  { title: "Beach bungalow studio off Rose", address: "535 Rose Ave", city: "Los Angeles", state: "CA", neighborhood: "Venice", rent: 2200, bedrooms: 0, bathrooms: 1, sqft: 510, amenities: "Hardwood floors, Outdoor shower, Shared garden", petFriendly: true, furnished: true, description: "Quintessential Venice beach bungalow with an outdoor shower and a sunny shared garden. Furnished and ready.", commuteNotes: "4 blocks to the sand; Lincoln Blvd buses nearby.", latitude: 33.9986, longitude: -118.4695 },

  // Mar Vista / Culver City
  { title: "Modern 2BR in Culver City", address: "9300 Culver Blvd", city: "Culver City", state: "CA", neighborhood: "Culver City", rent: 3500, bedrooms: 2, bathrooms: 2, sqft: 1150, amenities: "Gym, Rooftop deck, In-unit laundry, EV charging, Parking", petFriendly: true, furnished: false, description: "Contemporary 2BR near the revitalized downtown Culver City, the Expo Line, and the tech campuses of Silicon Beach.", commuteNotes: "8 min walk to Culver City Expo station; near the 10 and 405.", latitude: 34.0094, longitude: -118.3965 },
  { title: "1BR near Sony Studios", address: "3825 Main St", city: "Culver City", state: "CA", neighborhood: "Culver City", rent: 2650, bedrooms: 1, bathrooms: 1, sqft: 720, amenities: "Pool, Gym, In-unit laundry, Controlled access", petFriendly: true, furnished: false, description: "Stylish 1BR in walkable downtown Culver City, surrounded by restaurants, the Kirk Douglas Theatre, and studio lots.", commuteNotes: "Expo Line and bus hub minutes away; quick to the Westside.", latitude: 34.0211, longitude: -118.3965 },

  // Westwood
  { title: "Student-friendly 1BR near UCLA", address: "10925 Kelton Ave", city: "Los Angeles", state: "CA", neighborhood: "Westwood", rent: 2500, bedrooms: 1, bathrooms: 1, sqft: 700, amenities: "On-site laundry, Controlled access, Parking, Study lounge", petFriendly: false, furnished: false, description: "Well-kept 1BR a few blocks from UCLA and Westwood Village. Quiet building popular with grad students and faculty.", commuteNotes: "Walk to campus; near future Westwood/UCLA Metro station.", latitude: 34.0573, longitude: -118.4426 },
  { title: "Shared-ready 3BR in Westwood", address: "640 Veteran Ave", city: "Los Angeles", state: "CA", neighborhood: "Westwood", rent: 4800, bedrooms: 3, bathrooms: 2, sqft: 1500, amenities: "In-unit laundry, Balcony, Parking, Dishwasher", petFriendly: false, furnished: false, description: "Spacious 3BR built for roommates, with three true bedrooms and a big shared living space. Steps from campus.", commuteNotes: "5 min walk to UCLA; major bus lines on Wilshire.", latitude: 34.0606, longitude: -118.4470 },

  // Mid-Wilshire / Miracle Mile
  { title: "Art-Deco 1BR on Miracle Mile", address: "5400 Wilshire Blvd", city: "Los Angeles", state: "CA", neighborhood: "Miracle Mile", rent: 2400, bedrooms: 1, bathrooms: 1, sqft: 750, amenities: "Pool, Gym, On-site laundry, Parking", petFriendly: true, furnished: false, description: "Classic Art-Deco building across from LACMA and the future Purple Line station. Tall windows and original detailing.", commuteNotes: "Wilshire/Fairfax Metro opening nearby; central to everything.", latitude: 34.0624, longitude: -118.3486 },
  { title: "2BR near The Grove", address: "200 N Fuller Ave", city: "Los Angeles", state: "CA", neighborhood: "Fairfax", rent: 3300, bedrooms: 2, bathrooms: 2, sqft: 1100, amenities: "In-unit laundry, Rooftop deck, Gym, Parking", petFriendly: true, furnished: false, description: "Updated 2BR a short walk from The Grove and the Original Farmers Market. Open layout with a private balcony.", commuteNotes: "Walk to Farmers Market; near the 3rd St and Fairfax buses.", latitude: 34.0760, longitude: -118.3614 },

  // Los Feliz
  { title: "Vintage 1BR near Griffith Park", address: "1923 Hillhurst Ave", city: "Los Angeles", state: "CA", neighborhood: "Los Feliz", rent: 2600, bedrooms: 1, bathrooms: 1, sqft: 760, amenities: "Hardwood floors, On-site laundry, Courtyard, Parking", petFriendly: true, furnished: false, description: "Character-rich 1BR in a 1930s courtyard building near the Griffith Observatory trailheads and Hillhurst cafes.", commuteNotes: "Buses on Hillhurst and Vermont; 15 min to DTLA.", latitude: 34.1075, longitude: -118.2879 },

  // Highland Park
  { title: "Updated 2BR in Highland Park", address: "5650 N Figueroa St", city: "Los Angeles", state: "CA", neighborhood: "Highland Park", rent: 2700, bedrooms: 2, bathrooms: 1, sqft: 980, amenities: "In-unit laundry, Dishwasher, Backyard, Parking", petFriendly: true, furnished: false, description: "Bright 2BR steps from the York Blvd and Figueroa restaurant rows. Private backyard and tons of natural light.", commuteNotes: "Highland Park Metro (L line) 6 min away; direct to DTLA & Pasadena.", latitude: 34.1108, longitude: -118.1903 },
  { title: "Craftsman studio off York", address: "5132 York Blvd", city: "Los Angeles", state: "CA", neighborhood: "Highland Park", rent: 1600, bedrooms: 0, bathrooms: 1, sqft: 460, amenities: "Hardwood floors, On-site laundry, Shared yard", petFriendly: true, furnished: false, description: "Cozy studio in a converted Craftsman on buzzy York Blvd, surrounded by coffee roasters, bars, and vintage shops.", commuteNotes: "Walk to York Blvd; Metro L line a few blocks south.", latitude: 34.1148, longitude: -118.1947 },

  // Pasadena
  { title: "Elegant 1BR near Old Town", address: "155 S Marengo Ave", city: "Pasadena", state: "CA", neighborhood: "Pasadena", rent: 2350, bedrooms: 1, bathrooms: 1, sqft: 740, amenities: "Pool, Gym, In-unit laundry, Parking", petFriendly: true, furnished: false, description: "Refined 1BR a few blocks from Old Town Pasadena's dining and the Metro. Tree-lined street with mountain views.", commuteNotes: "Memorial Park Metro (A line) 7 min away; direct to DTLA.", latitude: 34.1456, longitude: -118.1488 },
  { title: "Roomy 2BR off Lake Ave", address: "275 N Lake Ave", city: "Pasadena", state: "CA", neighborhood: "Pasadena", rent: 3100, bedrooms: 2, bathrooms: 2, sqft: 1180, amenities: "In-unit laundry, Balcony, Gym, Parking, EV charging", petFriendly: true, furnished: false, description: "Generous 2BR near the Lake Ave shopping district and Caltech. Updated kitchen and a sunny balcony.", commuteNotes: "Lake Metro (A line) close by; quick 210 access.", latitude: 34.1542, longitude: -118.1316 },

  // Studio City / Sherman Oaks (Valley)
  { title: "1BR on Ventura Blvd", address: "12150 Ventura Blvd", city: "Studio City", state: "CA", neighborhood: "Studio City", rent: 2400, bedrooms: 1, bathrooms: 1, sqft: 780, amenities: "Pool, Gym, In-unit laundry, Parking, Controlled access", petFriendly: true, furnished: false, description: "Bright 1BR on the Studio City stretch of Ventura Blvd, walkable to Trader Joe's, sushi row, and the farmers market.", commuteNotes: "Universal City Metro (B line) 8 min; over the hill to Hollywood.", latitude: 34.1432, longitude: -118.3962 },
  { title: "2BR near Sherman Oaks Galleria", address: "15010 Moorpark St", city: "Sherman Oaks", state: "CA", neighborhood: "Sherman Oaks", rent: 2900, bedrooms: 2, bathrooms: 2, sqft: 1120, amenities: "Pool, Gym, In-unit laundry, Two-car parking, Balcony", petFriendly: true, furnished: false, description: "Quiet 2BR on a leafy street near the Galleria and Ventura Blvd dining. Big closets and a shaded balcony.", commuteNotes: "Near the 101 and 405 junction; ample street and gated parking.", latitude: 34.1517, longitude: -118.4490 },

  // Marina del Rey / Playa Vista
  { title: "Waterfront 1BR in Marina del Rey", address: "4314 Marina City Dr", city: "Marina del Rey", state: "CA", neighborhood: "Marina del Rey", rent: 3200, bedrooms: 1, bathrooms: 1, sqft: 820, amenities: "Marina views, Pool, Gym, Tennis, Concierge", petFriendly: true, furnished: false, description: "Resort-style 1BR overlooking the boat slips, with pools, tennis, and a waterfront promenade at your door.", commuteNotes: "Bike path to Venice and Santa Monica; near the 90 freeway.", latitude: 33.9776, longitude: -118.4517 },
  { title: "Tech-corridor 2BR in Playa Vista", address: "12760 Millennium Dr", city: "Los Angeles", state: "CA", neighborhood: "Playa Vista", rent: 4100, bedrooms: 2, bathrooms: 2, sqft: 1280, amenities: "Smart home, Pool, Gym, EV charging, Co-working lounge", petFriendly: true, furnished: false, description: "Brand-new 2BR in 'Silicon Beach' near the Google and YouTube campuses. Co-working lounge and resort amenities.", commuteNotes: "Shuttle to Westside tech; quick 405 and LAX access.", latitude: 33.9750, longitude: -118.4258 },

  // West LA / Sawtelle / Brentwood
  { title: "1BR in Sawtelle Japantown", address: "2025 Sawtelle Blvd", city: "Los Angeles", state: "CA", neighborhood: "Sawtelle / West LA", rent: 2700, bedrooms: 1, bathrooms: 1, sqft: 750, amenities: "In-unit laundry, Gym, Rooftop deck, Parking", petFriendly: true, furnished: false, description: "Modern 1BR in the heart of Sawtelle's ramen and boba corridor. Walk to dozens of restaurants and Nuart cinema.", commuteNotes: "Near the 405 and Expo Line at Sepulveda; minutes to UCLA.", latitude: 34.0469, longitude: -118.4452 },
  { title: "Quiet 2BR in Brentwood", address: "11740 Wilshire Blvd", city: "Los Angeles", state: "CA", neighborhood: "Brentwood", rent: 3800, bedrooms: 2, bathrooms: 2, sqft: 1200, amenities: "Pool, Gym, In-unit laundry, Concierge, Parking", petFriendly: true, furnished: false, description: "Serene 2BR on the Brentwood-Wilshire corridor near the VA, the Getty, and San Vicente's jogging path.", commuteNotes: "Rapid buses on Wilshire; close to the 405.", latitude: 34.0470, longitude: -118.4636 },

  // Atwater Village / Glassell Park (Eastside)
  { title: "Charming 1BR in Atwater Village", address: "3215 Glendale Blvd", city: "Los Angeles", state: "CA", neighborhood: "Atwater Village", rent: 2250, bedrooms: 1, bathrooms: 1, sqft: 700, amenities: "Hardwood floors, In-unit laundry, Shared patio, Parking", petFriendly: true, furnished: false, description: "Walkable 1BR on Atwater's main drag near the river bike path, indie shops, and Sunday farmers market.", commuteNotes: "L.A. River bike path to Griffith Park; 15 min to DTLA.", latitude: 34.1170, longitude: -118.2613 },

  // Long Beach (LA County)
  { title: "Downtown Long Beach 1BR", address: "150 Pine Ave", city: "Long Beach", state: "CA", neighborhood: "Downtown Long Beach", rent: 2050, bedrooms: 1, bathrooms: 1, sqft: 760, amenities: "Pool, Gym, Rooftop deck, In-unit laundry, Parking", petFriendly: true, furnished: false, description: "Bright 1BR on the Pine Ave entertainment corridor, blocks from the waterfront, the aquarium, and the Pike.", commuteNotes: "Metro A line to DTLA; walk to the beach and Shoreline Village.", latitude: 33.7690, longitude: -118.1925 },
  { title: "Belmont Shore studio", address: "5125 E 2nd St", city: "Long Beach", state: "CA", neighborhood: "Belmont Shore", rent: 1700, bedrooms: 0, bathrooms: 1, sqft: 500, amenities: "On-site laundry, Bike storage, Controlled access", petFriendly: true, furnished: false, description: "Beachy studio a block from the sand on 2nd Street, surrounded by Belmont Shore's cafes and shops.", commuteNotes: "Walk to the beach; bus lines along 2nd St.", latitude: 33.7592, longitude: -118.1247 },

  // Inglewood (near stadiums)
  { title: "2BR near SoFi Stadium", address: "3450 W Century Blvd", city: "Inglewood", state: "CA", neighborhood: "Inglewood", rent: 2600, bedrooms: 2, bathrooms: 2, sqft: 1000, amenities: "In-unit laundry, Gym, Parking, Controlled access", petFriendly: true, furnished: false, description: "Updated 2BR minutes from SoFi Stadium, the Forum, and the Intuit Dome. Great value for the Westside-adjacent location.", commuteNotes: "Metro K line nearby; quick 405 and LAX access.", latitude: 33.9456, longitude: -118.3372 },

  // Glendale
  { title: "1BR near the Americana", address: "350 N Central Ave", city: "Glendale", state: "CA", neighborhood: "Glendale", rent: 2400, bedrooms: 1, bathrooms: 1, sqft: 780, amenities: "Pool, Gym, In-unit laundry, Concierge, Parking", petFriendly: true, furnished: false, description: "Polished 1BR steps from the Americana at Brand and the Glendale Galleria. Walkable dining and shopping galore.", commuteNotes: "Near the 134 and 5; express buses to DTLA.", latitude: 34.1497, longitude: -118.2553 },

  // Burbank
  { title: "2BR near the studios in Burbank", address: "300 E Verdugo Ave", city: "Burbank", state: "CA", neighborhood: "Burbank", rent: 2950, bedrooms: 2, bathrooms: 2, sqft: 1080, amenities: "Pool, Gym, In-unit laundry, Two-car parking", petFriendly: true, furnished: false, description: "Comfortable 2BR near Warner Bros., Disney, and downtown Burbank's restaurants and AMC. Great for industry roommates.", commuteNotes: "Walk to Burbank Town Center; near the 5 and Metro.", latitude: 34.1779, longitude: -118.3076 },

  // Mid-City
  { title: "Spacious 1BR in Mid-City", address: "4900 W Pico Blvd", city: "Los Angeles", state: "CA", neighborhood: "Mid-City", rent: 2150, bedrooms: 1, bathrooms: 1, sqft: 760, amenities: "On-site laundry, Dishwasher, Parking, Controlled access", petFriendly: true, furnished: false, description: "Roomy 1BR central to everything — equidistant to DTLA, the Westside, and Hollywood. Big windows and good light.", commuteNotes: "Pico and La Brea buses; quick to the 10 freeway.", latitude: 34.0476, longitude: -118.3470 },

  // El Segundo (South Bay tech)
  { title: "Modern 2BR in El Segundo", address: "400 Main St", city: "El Segundo", state: "CA", neighborhood: "El Segundo", rent: 3400, bedrooms: 2, bathrooms: 2, sqft: 1150, amenities: "Rooftop deck, Gym, In-unit laundry, EV charging, Parking", petFriendly: true, furnished: false, description: "New-construction 2BR in walkable downtown El Segundo, near the aerospace and tech campuses of the South Bay.", commuteNotes: "Metro C/K lines nearby; minutes to LAX and the 105.", latitude: 33.9192, longitude: -118.4165 },

  // Hermosa / Redondo Beach
  { title: "Beach-close 1BR in Hermosa", address: "1200 Hermosa Ave", city: "Hermosa Beach", state: "CA", neighborhood: "Hermosa Beach", rent: 2900, bedrooms: 1, bathrooms: 1, sqft: 720, amenities: "In-unit laundry, Balcony, Bike storage, Parking", petFriendly: true, furnished: false, description: "Sunny 1BR two blocks from the Strand and the Hermosa pier. Surf-town vibe with cafes and bars at your door.", commuteNotes: "Walk to the beach; close to PCH and the 405.", latitude: 33.8649, longitude: -118.3993 },
];
